pub mod tags {
    pub const DEFS: &[&str] = &[
        "a",
        "altGlyph",
        "altGlyphDef",
        "altGlyphItem",
        "animate",
        "animateColor",
        "animateMotion",
        "animateTransform",
        "animation",
        "audio",
        "canvas",
        "circle",
        "clipPath",
        "color-profile",
        "cursor",
        "defs",
        "desc",
        "discard",
        "ellipse",
        "feBlend",
        "feColorMatrix",
        "feComponentTransfer",
        "feComposite",
        "feConvolveMatrix",
        "feDiffuseLighting",
        "feDisplacementMap",
        "feDistantLight",
        "feDropShadow",
        "feFlood",
        "feFuncA",
        "feFuncB",
        "feFuncG",
        "feFuncR",
        "feGaussianBlur",
        "feImage",
        "feMerge",
        "feMergeNode",
        "feMorphology",
        "feOffset",
        "fePointLight",
        "feSpecularLighting",
        "feSpotLight",
        "feTile",
        "feTurbulence",
        "filter",
        "font",
        "font-face",
        "font-face-format",
        "font-face-name",
        "font-face-src",
        "font-face-uri",
        "foreignObject",
        "g",
        "glyph",
        "glyphRef",
        "handler",
        "hkern",
        "iframe",
        "image",
        "line",
        "linearGradient",
        "listener",
        "marker",
        "mask",
        "metadata",
        "missing-glyph",
        "mpath",
        "path",
        "pattern",
        "polygon",
        "polyline",
        "prefetch",
        "radialGradient",
        "rect",
        "script",
        "set",
        "solidColor",
        "stop",
        "style",
        "svg",
        "switch",
        "symbol",
        "tbreak",
        "text",
        "textArea",
        "textPath",
        "title",
        "tref",
        "tspan",
        "unknown",
        "use",
        "video",
        "view",
        "vkern",
    ];
}

pub mod attrs {
    // This import path is altered because this file is included from build.rs
    use crate::attr_type::flags::*;

    pub const DEFS: &[(&str, &str, u32)] = &[
        ("about", "about", COMMA_SEP | SPACE_SEP),
        ("accent-height", "accentHeight", NUMBER),
        ("accumulate", "accumulate", STRING),
        ("additive", "additive", STRING),
        ("alignment-baseline", "alignmentBaseline", STRING),
        ("alphabetic", "alphabetic", NUMBER),
        ("amplitude", "amplitude", NUMBER),
        ("arabic-form", "arabicForm", STRING),
        ("ascent", "ascent", NUMBER),
        ("attributeName", "attributeName", STRING),
        ("attributeType", "attributeType", STRING),
        ("azimuth", "azimuth", NUMBER),
        ("bandwidth", "bandwidth", STRING),
        ("baseline-shift", "baselineShift", STRING),
        ("baseFrequency", "baseFrequency", STRING),
        ("baseProfile", "baseProfile", STRING),
        ("bbox", "bbox", STRING),
        ("begin", "begin", STRING),
        ("bias", "bias", NUMBER),
        ("by", "by", STRING),
        ("calcMode", "calcMode", STRING),
        ("cap-height", "capHeight", NUMBER),
        ("class", "className", SPACE_SEP),
        ("clip", "clip", STRING),
        ("clip-path", "clipPath", STRING),
        ("clipPathUnits", "clipPathUnits", STRING),
        ("clip-rule", "clipRule", STRING),
        ("color", "color", STRING),
        ("color-interpolation", "colorInterpolation", STRING),
        (
            "color-interpolation-filters",
            "colorInterpolationFilters",
            STRING,
        ),
        ("color-profile", "colorProfile", STRING),
        ("color-rendering", "colorRendering", STRING),
        ("content", "content", STRING),
        ("contentScriptType", "contentScriptType", STRING),
        ("contentStyleType", "contentStyleType", STRING),
        ("crossorigin", "crossOrigin", STRING),
        ("cursor", "cursor", STRING),
        ("cx", "cx", STRING),
        ("cy", "cy", STRING),
        ("d", "d", STRING),
        ("datatype", "dataType", STRING),
        ("defaultAction", "defaultAction", STRING),
        ("descent", "descent", NUMBER),
        ("diffuseConstant", "diffuseConstant", NUMBER),
        ("direction", "direction", STRING),
        ("display", "display", STRING),
        ("dur", "dur", STRING),
        ("divisor", "divisor", NUMBER),
        ("dominant-baseline", "dominantBaseline", STRING),
        ("download", "download", BOOL),
        ("dx", "dx", STRING),
        ("dy", "dy", STRING),
        ("edgeMode", "edgeMode", STRING),
        ("editable", "editable", STRING),
        ("elevation", "elevation", NUMBER),
        ("enable-background", "enableBackground", STRING),
        ("end", "end", STRING),
        ("event", "event", STRING),
        ("exponent", "exponent", NUMBER),
        (
            "externalResourcesRequired",
            "externalResourcesRequired",
            STRING,
        ),
        ("fill", "fill", STRING),
        ("fill-opacity", "fillOpacity", NUMBER),
        ("fill-rule", "fillRule", STRING),
        ("filter", "filter", STRING),
        ("filterRes", "filterRes", STRING),
        ("filterUnits", "filterUnits", STRING),
        ("flood-color", "floodColor", STRING),
        ("flood-opacity", "floodOpacity", STRING),
        ("focusable", "focusable", STRING),
        ("focusHighlight", "focusHighlight", STRING),
        ("font-family", "fontFamily", STRING),
        ("font-size", "fontSize", STRING),
        ("font-size-adjust", "fontSizeAdjust", STRING),
        ("font-stretch", "fontStretch", STRING),
        ("font-style", "fontStyle", STRING),
        ("font-variant", "fontVariant", STRING),
        ("font-weight", "fontWeight", STRING),
        ("format", "format", STRING),
        ("fr", "fr", STRING),
        ("from", "from", STRING),
        ("fx", "fx", STRING),
        ("fy", "fy", STRING),
        ("g1", "g1", COMMA_SEP),
        ("g2", "g2", COMMA_SEP),
        ("glyph-name", "glyphName", COMMA_SEP),
        (
            "glyph-orientation-horizontal",
            "glyphOrientationHorizontal",
            STRING,
        ),
        (
            "glyph-orientation-vertical",
            "glyphOrientationVertical",
            STRING,
        ),
        ("glyphRef", "glyphRef", STRING),
        ("gradientTransform", "gradientTransform", STRING),
        ("gradientUnits", "gradientUnits", STRING),
        ("handler", "handler", STRING),
        ("hanging", "hanging", NUMBER),
        ("hatchContentUnits", "hatchContentUnits", STRING),
        ("hatchUnits", "hatchUnits", STRING),
        ("height", "height", STRING),
        ("href", "href", STRING),
        ("hreflang", "hrefLang", STRING),
        ("horiz-adv-x", "horizAdvX", NUMBER),
        ("horiz-origin-x", "horizOriginX", NUMBER),
        ("horiz-origin-y", "horizOriginY", NUMBER),
        ("id", "id", STRING),
        ("ideographic", "ideographic", NUMBER),
        ("image-rendering", "imageRendering", STRING),
        ("initialVisibility", "initialVisibility", STRING),
        ("in", "in", STRING),
        ("in2", "in2", STRING),
        ("intercept", "intercept", NUMBER),
        ("k", "k", NUMBER),
        ("k1", "k1", NUMBER),
        ("k2", "k2", NUMBER),
        ("k3", "k3", NUMBER),
        ("k4", "k4", NUMBER),
        ("kernelMatrix", "kernelMatrix", COMMA_SEP | SPACE_SEP),
        ("kernelUnitLength", "kernelUnitLength", STRING),
        ("keyPoints", "keyPoints", STRING),
        ("keySplines", "keySplines", STRING),
        ("keyTimes", "keyTimes", STRING),
        ("kerning", "kerning", STRING),
        ("lang", "lang", STRING),
        ("lengthAdjust", "lengthAdjust", STRING),
        ("letter-spacing", "letterSpacing", STRING),
        ("lighting-color", "lightingColor", STRING),
        ("limitingConeAngle", "limitingConeAngle", NUMBER),
        ("local", "local", STRING),
        ("marker-end", "markerEnd", STRING),
        ("marker-mid", "markerMid", STRING),
        ("marker-start", "markerStart", STRING),
        ("markerHeight", "markerHeight", STRING),
        ("markerUnits", "markerUnits", STRING),
        ("markerWidth", "markerWidth", STRING),
        ("mask", "mask", STRING),
        ("maskContentUnits", "maskContentUnits", STRING),
        ("maskUnits", "maskUnits", STRING),
        ("mathematical", "mathematical", STRING),
        ("max", "max", STRING),
        ("media", "media", STRING),
        ("mediaCharacterEncoding", "mediaCharacterEncoding", STRING),
        ("mediaContentEncodings", "mediaContentEncodings", STRING),
        ("mediaSize", "mediaSize", NUMBER),
        ("mediaTime", "mediaTime", STRING),
        ("method", "method", STRING),
        ("min", "min", STRING),
        ("mode", "mode", STRING),
        ("name", "name", STRING),
        ("nav-down", "navDown", STRING),
        ("nav-down-left", "navDownLeft", STRING),
        ("nav-down-right", "navDownRight", STRING),
        ("nav-left", "navLeft", STRING),
        ("nav-next", "navNext", STRING),
        ("nav-prev", "navPrev", STRING),
        ("nav-right", "navRight", STRING),
        ("nav-up", "navUp", STRING),
        ("nav-up-left", "navUpLeft", STRING),
        ("nav-up-right", "navUpRight", STRING),
        ("numOctaves", "numOctaves", STRING),
        ("observer", "observer", STRING),
        ("offset", "offset", STRING),
        ("onabort", "onAbort", STRING),
        ("onactivate", "onActivate", STRING),
        ("onafterprint", "onAfterPrint", STRING),
        ("onbeforeprint", "onBeforePrint", STRING),
        ("onbegin", "onBegin", STRING),
        ("oncancel", "onCancel", STRING),
        ("oncanplay", "onCanPlay", STRING),
        ("oncanplaythrough", "onCanPlayThrough", STRING),
        ("onchange", "onChange", STRING),
        ("onclick", "onClick", STRING),
        ("onclose", "onClose", STRING),
        ("oncopy", "onCopy", STRING),
        ("oncuechange", "onCueChange", STRING),
        ("oncut", "onCut", STRING),
        ("ondblclick", "onDblClick", STRING),
        ("ondrag", "onDrag", STRING),
        ("ondragend", "onDragEnd", STRING),
        ("ondragenter", "onDragEnter", STRING),
        ("ondragexit", "onDragExit", STRING),
        ("ondragleave", "onDragLeave", STRING),
        ("ondragover", "onDragOver", STRING),
        ("ondragstart", "onDragStart", STRING),
        ("ondrop", "onDrop", STRING),
        ("ondurationchange", "onDurationChange", STRING),
        ("onemptied", "onEmptied", STRING),
        ("onend", "onEnd", STRING),
        ("onended", "onEnded", STRING),
        ("onerror", "onError", STRING),
        ("onfocus", "onFocus", STRING),
        ("onfocusin", "onFocusIn", STRING),
        ("onfocusout", "onFocusOut", STRING),
        ("onhashchange", "onHashChange", STRING),
        ("oninput", "onInput", STRING),
        ("oninvalid", "onInvalid", STRING),
        ("onkeydown", "onKeyDown", STRING),
        ("onkeypress", "onKeyPress", STRING),
        ("onkeyup", "onKeyUp", STRING),
        ("onload", "onLoad", STRING),
        ("onloadeddata", "onLoadedData", STRING),
        ("onloadedmetadata", "onLoadedMetadata", STRING),
        ("onloadstart", "onLoadStart", STRING),
        ("onmessage", "onMessage", STRING),
        ("onmousedown", "onMouseDown", STRING),
        ("onmouseenter", "onMouseEnter", STRING),
        ("onmouseleave", "onMouseLeave", STRING),
        ("onmousemove", "onMouseMove", STRING),
        ("onmouseout", "onMouseOut", STRING),
        ("onmouseover", "onMouseOver", STRING),
        ("onmouseup", "onMouseUp", STRING),
        ("onmousewheel", "onMouseWheel", STRING),
        ("onoffline", "onOffline", STRING),
        ("ononline", "onOnline", STRING),
        ("onpagehide", "onPageHide", STRING),
        ("onpageshow", "onPageShow", STRING),
        ("onpaste", "onPaste", STRING),
        ("onpause", "onPause", STRING),
        ("onplay", "onPlay", STRING),
        ("onplaying", "onPlaying", STRING),
        ("onpopstate", "onPopState", STRING),
        ("onprogress", "onProgress", STRING),
        ("onratechange", "onRateChange", STRING),
        ("onrepeat", "onRepeat", STRING),
        ("onreset", "onReset", STRING),
        ("onresize", "onResize", STRING),
        ("onscroll", "onScroll", STRING),
        ("onseeked", "onSeeked", STRING),
        ("onseeking", "onSeeking", STRING),
        ("onselect", "onSelect", STRING),
        ("onshow", "onShow", STRING),
        ("onstalled", "onStalled", STRING),
        ("onstorage", "onStorage", STRING),
        ("onsubmit", "onSubmit", STRING),
        ("onsuspend", "onSuspend", STRING),
        ("ontimeupdate", "onTimeUpdate", STRING),
        ("ontoggle", "onToggle", STRING),
        ("onunload", "onUnload", STRING),
        ("onvolumechange", "onVolumeChange", STRING),
        ("onwaiting", "onWaiting", STRING),
        ("onzoom", "onZoom", STRING),
        ("opacity", "opacity", STRING),
        ("operator", "operator", STRING),
        ("order", "order", STRING),
        ("orient", "orient", STRING),
        ("orientation", "orientation", STRING),
        ("origin", "origin", STRING),
        ("overflow", "overflow", STRING),
        ("overlay", "overlay", STRING),
        ("overline-position", "overlinePosition", NUMBER),
        ("overline-thickness", "overlineThickness", NUMBER),
        ("paint-order", "paintOrder", STRING),
        ("panose-1", "panose1", STRING),
        ("path", "path", STRING),
        ("pathLength", "pathLength", NUMBER),
        ("patternContentUnits", "patternContentUnits", STRING),
        ("patternTransform", "patternTransform", STRING),
        ("patternUnits", "patternUnits", STRING),
        ("phase", "phase", STRING),
        ("ping", "ping", SPACE_SEP),
        ("pitch", "pitch", STRING),
        ("playbackorder", "playbackOrder", STRING),
        ("pointer-events", "pointerEvents", STRING),
        ("points", "points", STRING),
        ("pointsAtX", "pointsAtX", NUMBER),
        ("pointsAtY", "pointsAtY", NUMBER),
        ("pointsAtZ", "pointsAtZ", NUMBER),
        ("preserveAlpha", "preserveAlpha", STRING),
        ("preserveAspectRatio", "preserveAspectRatio", STRING),
        ("primitiveUnits", "primitiveUnits", STRING),
        ("propagate", "propagate", STRING),
        ("property", "property", COMMA_SEP | SPACE_SEP),
        ("r", "r", STRING),
        ("radius", "radius", STRING),
        ("referrerpolicy", "referrerPolicy", STRING),
        ("refX", "refX", STRING),
        ("refY", "refY", STRING),
        ("rel", "rel", COMMA_SEP | SPACE_SEP),
        ("rev", "rev", COMMA_SEP | SPACE_SEP),
        ("rendering-intent", "renderingIntent", STRING),
        ("repeatCount", "repeatCount", STRING),
        ("repeatDur", "repeatDur", STRING),
        (
            "requiredExtensions",
            "requiredExtensions",
            COMMA_SEP | SPACE_SEP,
        ),
        (
            "requiredFeatures",
            "requiredFeatures",
            COMMA_SEP | SPACE_SEP,
        ),
        ("requiredFonts", "requiredFonts", COMMA_SEP | SPACE_SEP),
        ("requiredFormats", "requiredFormats", COMMA_SEP | SPACE_SEP),
        ("resource", "resource", STRING),
        ("restart", "restart", STRING),
        ("result", "result", STRING),
        ("rotate", "rotate", STRING),
        ("rx", "rx", STRING),
        ("ry", "ry", STRING),
        ("scale", "scale", STRING),
        ("seed", "seed", STRING),
        ("shape-rendering", "shapeRendering", STRING),
        ("side", "side", STRING),
        ("slope", "slope", STRING),
        ("snapshotTime", "snapshotTime", STRING),
        ("specularConstant", "specularConstant", NUMBER),
        ("specularExponent", "specularExponent", NUMBER),
        ("spreadMethod", "spreadMethod", STRING),
        ("spacing", "spacing", STRING),
        ("startOffset", "startOffset", STRING),
        ("stdDeviation", "stdDeviation", STRING),
        ("stemh", "stemh", STRING),
        ("stemv", "stemv", STRING),
        ("stitchTiles", "stitchTiles", STRING),
        ("stop-color", "stopColor", STRING),
        ("stop-opacity", "stopOpacity", STRING),
        ("strikethrough-position", "strikethroughPosition", NUMBER),
        ("strikethrough-thickness", "strikethroughThickness", NUMBER),
        ("string", "string", STRING),
        ("stroke", "stroke", STRING),
        ("stroke-dasharray", "strokeDashArray", COMMA_SEP | SPACE_SEP),
        ("stroke-dashoffset", "strokeDashOffset", STRING),
        ("stroke-linecap", "strokeLineCap", STRING),
        ("stroke-linejoin", "strokeLineJoin", STRING),
        ("stroke-miterlimit", "strokeMiterLimit", NUMBER),
        ("stroke-opacity", "strokeOpacity", NUMBER),
        ("stroke-width", "strokeWidth", STRING),
        ("style", "style", STRING),
        ("surfaceScale", "surfaceScale", NUMBER),
        ("syncBehavior", "syncBehavior", STRING),
        ("syncBehaviorDefault", "syncBehaviorDefault", STRING),
        ("syncMaster", "syncMaster", STRING),
        ("syncTolerance", "syncTolerance", STRING),
        ("syncToleranceDefault", "syncToleranceDefault", STRING),
        ("systemLanguage", "systemLanguage", COMMA_SEP | SPACE_SEP),
        ("tabindex", "tabIndex", NUMBER),
        ("tableValues", "tableValues", STRING),
        ("target", "target", STRING),
        ("targetX", "targetX", NUMBER),
        ("targetY", "targetY", NUMBER),
        ("text-anchor", "textAnchor", STRING),
        ("text-decoration", "textDecoration", STRING),
        ("text-rendering", "textRendering", STRING),
        ("textLength", "textLength", STRING),
        ("timelinebegin", "timelineBegin", STRING),
        ("title", "title", STRING),
        ("transformBehavior", "transformBehavior", STRING),
        ("type", "type", STRING),
        ("typeof", "typeOf", COMMA_SEP | SPACE_SEP),
        ("to", "to", STRING),
        ("transform", "transform", STRING),
        ("u1", "u1", STRING),
        ("u2", "u2", STRING),
        ("underline-position", "underlinePosition", NUMBER),
        ("underline-thickness", "underlineThickness", NUMBER),
        ("unicode", "unicode", STRING),
        ("unicode-bidi", "unicodeBidi", STRING),
        ("unicode-range", "unicodeRange", STRING),
        ("units-per-em", "unitsPerEm", NUMBER),
        ("values", "values", STRING),
        ("v-alphabetic", "vAlphabetic", NUMBER),
        ("v-mathematical", "vMathematical", NUMBER),
        ("vector-effect", "vectorEffect", STRING),
        ("v-hanging", "vHanging", NUMBER),
        ("v-ideographic", "vIdeographic", NUMBER),
        ("version", "version", STRING),
        ("vert-adv-y", "vertAdvY", NUMBER),
        ("vert-origin-x", "vertOriginX", NUMBER),
        ("vert-origin-y", "vertOriginY", NUMBER),
        ("viewBox", "viewBox", STRING),
        ("viewTarget", "viewTarget", STRING),
        ("visibility", "visibility", STRING),
        ("width", "width", STRING),
        ("widths", "widths", STRING),
        ("word-spacing", "wordSpacing", STRING),
        ("writing-mode", "writingMode", STRING),
        ("x", "x", STRING),
        ("x1", "x1", STRING),
        ("x2", "x2", STRING),
        ("xChannelSelector", "xChannelSelector", STRING),
        ("x-height", "xHeight", NUMBER),
        ("y", "y", STRING),
        ("y1", "y1", STRING),
        ("y2", "y2", STRING),
        ("yChannelSelector", "yChannelSelector", STRING),
        ("z", "z", STRING),
        ("zoomAndPan", "zoomAndPan", STRING),
    ];
}
